spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/community
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  servlet:
    context-path: /
  port: 8081

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml


#logging:
#  level:
#    com.gyy.boot: debug
#    org.springframework: error
